name: Tests
on: [ push ]

jobs:
  ts-test:
    name: Test Typescript Solutions
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Difficult/soc-opt
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"

      - name: Init npm
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Run ESLint
        run: npm run lint